version: "3.8"

services:

  db:
    image: postgres:15
    container_name: bank-db
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: bank-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: bank-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: