spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:bankdb}
spring.datasource.username=${DB_USER:bankuser}
spring.datasource.password=${DB_PASS:bankpass}

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,prometheus